longevity_dbt:
  outputs:
    dev:
      type: duckdb
      path: C:\Users\Carter Dakota\portfolio\longevity-drugs-analysis\longevity-drugs\duckdb_database\drug_age.db
      # extensions:
      #   - httpfs
      #   - parquet
      # settings:
      #   s3_region: my-aws-region
      #   s3_access_key_id: "{{ env_var('S3_ACCESS_KEY_ID') }}"
      #   s3_secret_access_key: "{{ env_var('S3_SECRET_ACCESS_KEY') }}"
  target: dev